# Site settings
title: Visan-MIG
email: visan-mig@smu.ca
description: > # this means to ignore newlines until "baseurl:"
  The two-year project "Visual analytics for text-intensive social science research on immigration" (VisAn-MIG) is based on harnessing an interdisciplinary research methodology bringing together computer science tools and social science qualitative methods in understanding changing perceptions and constructions of immigrants and refugees in Canada in the last two centuries.
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages

# Collections configuration
collections:
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title/

# Standard pagination settings
paginate: 10
paginate_path: "/news/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Sass settings
sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true