name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'
          bundler-cache: true

      # Add this step to unfreeze the bundle
      - name: Unfreeze bundle
        run: bundle config --local frozen false

      - name: Install dependencies
        run: bundle install

      - name: Build and Deploy
        uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
          jekyll_src: './'